### ISSUE TITLE
Mobile Search Not working

### ISSUE THREAD

**Issue by rahul20110** [gaby/ABS#16]
It seems that the mobile search is not working. I have to download another user agent switcher to run the searches. It is not accepting the delay time. From 9th Jan 2023, it has been behaving weirdly to be honest.

**Comment by Rutvikballar** [comment]
It Has Simple Solution Do As I Say. Open New Tab And Goto More Tool And Then Developer tools And Then Ctrl + Shift + M. And Then Search WIth ABS Or Search Manually
