### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by iambadash01** [gaby/ABS#17]
extension is not working properly in browser please update it.

**Comment by rahul20110** [comment]
Yeah it is creating many problems

**Comment by iambadash01** [comment]
> Yeah it is creating many problems

Did you find any solutions

**Comment by rahul20110** [comment]
Not till now, but I am trying to find it. Even I tried to export it in manifest v3 but doing that, it lost the main feature i.e. automatic. so I gave up on this :(

**Comment by iambadash01** [comment]
> Not till now, but I am trying to find it. Even I tried to export it in manifest v3 but doing that, it lost the main feature i.e. automatic. so I gave up on this :(

How many accounts do you have, did you ever get banned if yes why?

**Comment by Akhilesh9878** [comment]
hii i am also facing many problem now. extension is not working fine after manifest 3 come

**Comment by gaby** [comment]
Duplicate of #10

**Comment by rahul20110** [comment]
@iambadash01 I Found the mistake. Now working properly
