### ISSUE TITLE
No longer able to farm after a certain number of points be it using a vpn or another account

### ISSUE THREAD

**Issue by Darkcupid292** [gaby/ABS#22]
after farming 500points on m main acc o longer able to farm more points even after i make a new account only able to reach till 199 and even if it does show me that i have earnd points its not added to my account

**Comment by gaby** [comment]
Could it be related to #21 ?

**Comment by evilmm** [comment]
Seems like they blocked the user agents listed at the bottom of constants.js . I pulled my current Edge desktop user agent and mobile and replaced it and it seems to be working again.

**Comment by VolkerSchlegel** [comment]
Works for me after updating user agents
New Desktop user agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61
New Mobile user agent: 
Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.80 Mobile Safari/537.36 EdgA/117.0.2045.65

**Comment by VolkerSchlegel** [comment]
Also they seem to have blocked my account from redeeming stuff (site says temporarily blocked, how long does that last?), so I'd recommend updating asap, I hope they just detected the user agent.

**Comment by VolkerSchlegel** [comment]
Redeemed something yesterday, just let the account sit there for around a week, I kept the points as well, so the ban is not really an issue.

Will update when I redeem something again if updating user agents alone helped.
