### ISSUE TITLE
No Longer giving Points

### ISSUE THREAD

**Issue by 2023SMHrailwaygames** [gaby/ABS#28]
The ABS Extension is no longer giving points. I have tried changing the modes and adjusting the delay ms.
The Microsoft Team might have fixed this.

**Comment by aKa-0z** [comment]
Seems like it, but I found another extension that works. Sadly it's terrible, but that means it's still possible.

**Comment by gaby** [comment]
Please check https://github.com/h4x0rm1k3/ABS
