### ISSUE TITLE
Has it been banned?

### ISSUE THREAD

**Issue by fghjkgcfxx56u** [gaby/ABS#5]
Both the Firefox and the Chrome link redirect to a 404 page and i can't find it one the web store either

**Comment by h4x0rm1k3** [comment]
It's banned on the store fronts but you can still install it manually in both Chrome & Firefox (Firefox has a few more hoops to jump through). You just need the files from Github and then in Chrome go to extensions page, turn on dev mode (top right toggle) and then you can load unpacked (top left) and point it to the src folder and it'll install. For Firefox you need to make a developer account, upload the files from Github (make them only available to yourself) and then wait a short while and it'll sign the files for you so you can install it manually.

**Comment by gaby** [comment]
@fghjkgcfxx56u Either banned or removed my the original developer.
