### ISSUE TITLE
Not opening Cards

### ISSUE THREAD

**Issue by LtCMDstone** [gaby/ABS#9]
Hey is it only me?
The auto searches and the Quizes, Polls are working fine.
But I have to open the "cards" manually, it seem the extension isn't clicking the cards, after I click them everything is as expected

**Comment by gaby** [comment]
@LtCMDstone Same for me in Chrome. It has been that way for months.

**Comment by h4x0rm1k3** [comment]
If you're still having issues with this then I fixed it a while back by adding a 3 minute delay so searches start first & complete within 3 minutes and then rewards will start up then. I found that searches were taking over the rewards tasks so rewards weren't completing. You need to edit the file open-rewards-tasks.js which is in the src/content-scripts folder and then replace lines 9-12 with the following - 

function clickAll(selector, parent = document) {
  const elements = [...parent.querySelectorAll(selector)];
  elements.forEach(e => 
    // wait 60 seconds between each "click", to ensure that the site correctly registers that it has been completed 
    // (it seems that quizzes and polls running at the same time do not get registered as completed)
    setTimeout(function() {
		        clickElement(e, true);
		    }, 180000)
	    );
}

**Comment by gaby** [comment]
Follow https://github.com/h4x0rm1k3/ABS for updates
